1D array creation (arange)

In [8]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Change Dimension (reshape)

In [9]:
arr=arr.reshape(5,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Multiplying two matrix (dot)

In [12]:
m1=np.random.random((5,4))
m2=np.random.random((4,5))
result=np.dot(m1,m2)
print(m1)
print(m2)
print(result)

[[0.21813107 0.206648   0.98046454 0.87825027]
 [0.49224596 0.18588291 0.50193854 0.99288321]
 [0.79868828 0.50432339 0.17598419 0.607268  ]
 [0.39644106 0.32602367 0.3985923  0.37962804]
 [0.91608127 0.02339415 0.40015289 0.73512086]]
[[0.73003629 0.28788311 0.63219117 0.07678365 0.91530273]
 [0.61656135 0.51703523 0.61800729 0.09006956 0.73873927]
 [0.72072014 0.307784   0.34719274 0.34728147 0.95673755]
 [0.54227965 0.122929   0.86668131 0.2043804  0.82742293]]
[[1.46955255 0.57937427 1.36718377 0.5553559  2.0170466 ]
 [1.3741432  0.51436011 1.46085328 0.43177865 1.88963086]
 [1.35016216 0.61949779 1.40400746 0.29198011 1.7744432 ]
 [0.98356802 0.45204204 0.91951642 0.27581725 1.29917124]
 [1.37023582 0.48934825 1.36964192 0.36165714 1.846871  ]]


Extract all odd numbers from an array of 1-10

In [14]:
arr=np.arange(1,11)
odd=arr[arr%2!=0]
print(odd)

[1 3 5 7 9]


Replace all odd numbers in an array of 1-10 with -1


In [17]:
arr=np.arange(1,11)
arr[arr%2!=0]=-1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


Create a random 3x3 matrix and normalize it.

In [20]:
matrix=np.random.random((3,3))
normalized=(matrix-np.mean(matrix))/np.std(matrix)
print(matrix)

[[0.4001178  0.81571648 0.53931882]
 [0.09493111 0.20159193 0.90458868]
 [0.45056229 0.46944842 0.49365171]]


Calculate the sum of the diagonal elements of a 3x3 matrix.

In [25]:
arr=np.random.random((3,3))
diagonal_sum=np.trace(arr)
print(arr)
print(diagonal_sum)

[[0.62369818 0.09934044 0.11672518]
 [0.11510596 0.41081103 0.46435988]
 [0.88946161 0.94643877 0.70839256]]
1.7429017694261468
